services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "5173:5173"
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile  

    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - database

  database:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local